### ISSUE TITLE
Export to csv

### ISSUE THREAD

**Issue by p2635** [SecUSo/privacy-friendly-pain-diary#13]
As title. This would be good so I have more control on the data and can view it on any spreadsheet software.

**Comment by petermayer** [comment]
Thanks for the suggestion, we will keep it in mind for future versions of the app.

**Comment by kelna** [comment]
And/or make it possible to export raw data so the user can migrate it to a new phone. Practically, CSV should be enough to do this as well. Thanks for the project though!
