### ISSUE TITLE
Calender Problem

### ISSUE THREAD

**Issue by RufioHugo** [SecUSo/privacy-friendly-pain-diary#17]
Hi!
Calender only goes back to 1970 ...

**Comment by Kamuno** [comment]
I can not really reproduce this Issue.. as far as I can see the DatePickerDialog goes back to 1900 allowing for every possible birth day. 

If you mean the main calendar for the diary - this calendar is supposed to work for present and future entries.

Could you tell us what device and android version you are using? This would help find the issue. 

There is a related google issue on DatePicker here:
https://issuetracker.google.com/issues/36937608

For now, as long as we don't have more information on this, this issue will be closed.

**Comment by RufioHugo** [comment]
Hi Kamuno!

- BQ M5 Android 7.1.2 (LineageOS 14.1) and earlier
- BQ U Android 7.1.1 and earlier

In both cases ...
User data => Date of birth (forgotten to declare that - sorry on that) => when scrolling it ends 1970

Regards RufioHugo
